### ISSUE TITLE
代码疑问

### ISSUE THREAD

**Issue by mfslog** [seata/seata-go-server#18]
代码中存在这样的情况：
代码片段一：
```go
if !tc.leader {
		return
	}

	c := acquireCMD()
	c.cmdType = cmdACKB
	c.ack = ack

	tc.cmds.Put(c)
```
代码片段二：
```go
if !tc.leader {
		cb(false, meta.ErrNotLeader)
		return
	}

	c := acquireCMD()
	c.cmdType = cmdLockable
	c.resource = resource
	c.gid = gid
	c.lockKeys = lockKeys
	c.boolCB = cb

	err := tc.cmds.Put(c)
	if err != nil {
		cb(false, err)
		releaseCMD(c)
	}
```

 代码片段一中没有判断消息入队列失败情况，代码片段二又判断了入队列失败的情况。
为啥会存在处理不一致的情况呢？代码片段一中的情况是不是遗漏了入队列失败情况下对消息的回收？

**Comment by zhangxu19830126** [comment]
代码片段对于seata的回复第二阶段的ACK消息，不需要处理失败的情况，如果失败，服务会ACK超时，会重新触发流程，重新给seata客户端发送第二阶段的回滚或者提交请求

**Comment by mfslog** [comment]
> 代码片段对于seata的回复第二阶段的ACK消息，不需要处理失败的情况，如果失败，服务会ACK超时，会重新触发流程，重新给seata客户端发送第二阶段的回滚或者提交请求

我的疑问不是流程上的疑问，是代码上的疑问。 前面描述的两个代码片段中，片段1没有在入队失败情况下调用releaseCMD , 片段二 在失败情况下调用了releaseCMD， 两处不一样的原因是什么呢？

**Comment by zhangxu19830126** [comment]
由于ACK不需要关注错误的情况，所以可以偷懒少写一点代码，对于正确性不产生影响。仅此而已。第二种情况，需要处理错误是因为需要调用callback，把错误告诉客户端。而 ACK的逻辑不需要回复客户端。

**Comment by mfslog** [comment]
> 由于ACK不需要关注错误的情况，所以可以偷懒少写一点代码，对于正确性不产生影响。仅此而已。第二种情况，需要处理错误是因为需要调用callback，把错误告诉客户端。而 ACK的逻辑不需要回复客户端。

了解；可以统一下吧。要么都回收到sync.pool， 要么都不回收了得了。
P.S. 多谢解答
